"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _overview_stats from './overview-stats.bones.json'
import _notes_stats from './notes-stats.bones.json'
import _products_table from './products-table.bones.json'
import _sales_table from './sales-table.bones.json'
import _notes_table from './notes-table.bones.json'

configureBoneyard({"color":"#e5e5e5","animate":"pulse","speed":"1.8s"})

registerBones({
  "overview-stats": _overview_stats,
  "notes-stats": _notes_stats,
  "products-table": _products_table,
  "sales-table": _sales_table,
  "notes-table": _notes_table,
})
